name             'concrete5'
maintainer       'Atsushi Nakajyo'
maintainer_email 'jyotti@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures concrete5'
long_description 'Installs/Configures concrete5'
version          '0.1.0'

depends 'yum-epel', '~> 0.6.0'
depends 'yum-ius', '~> 0.4.0'
depends 'timezone-ii', '~> 0.2.0'
depends 'nginx', '~> 2.7.4'
depends 'mysql', '~> 6.0'
depends 'ark', '~> 0.9'
